version: "3.8"

services:

  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - kafka
    env_file:
      - .env
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "29092:29092"  # External access for local producers/consumers
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  socket:
    build: ./kafka/socket  # Path to socket server
    depends_on:
      - kafka
    ports:
      - "5050:5050"
    networks:
      - app-network

  producer:
    build: ./kafka/producer  # Path to producer folder
    depends_on:
      - kafka
      - socket
    networks:
      - app-network

  consumer:
    build: ./kafka/consumer  # Path to consumer folder
    depends_on:
      - kafka
      - producer
      - mongo
    environment:
      # MongoDB Atlas connection for consumer
      - DATABASE_URL=mongodb+srv://guthidivya:Chandan25@cluster0.r1qau.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
